export const SEARCH_VIDEO = 'SEARCH_VIDEO'
export const PLAY_VIDEO = 'PLAY_VIDEO'
export const SAVE_VIDEO = 'SAVE_VIDEO'
export const GET_HISTORY = 'GET_HISTORY'
export const DELETE_VIDEO = 'DELETE_VIDEO'
